/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import AccesoDatos.ProductSaleModel;
import AccesoDatos.UserModel;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class HistorySales extends javax.swing.JFrame {

    private ArrayList<ProductSaleModel> sales;
    private UserModel user;

    public HistorySales(UserModel user) {
        initComponents();

        this.setVisible(true);
        this.user = user;

        this.populateTable();

        this.setTitle("Historial");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Numero Venta", "Fecha", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int selected = this.table.getSelectedRow();

        ProductSaleModel sale = this.sales.get(selected);

        Invoice invoice = new Invoice(sale.getProducts(), this.user);

    }//GEN-LAST:event_tableMouseClicked

    private void populateTable() {
        ProductSaleModel s = new ProductSaleModel(this.user.getId());

        this.sales = s.getHistoryUser();

        String columns[] = {"Numero Venta", "Fecha", "Total"};
        String data[][] = new String[this.sales.size()][columns.length];

        for (int i = 0; i < this.sales.size(); i++) {
            data[i][0] = String.valueOf(i + 1);
            data[i][1] = this.sales.get(i).getDate();
            data[i][2] = this.sales.get(i).getTotal();
        }

        DefaultTableModel dataModel = new DefaultTableModel(data, columns);
        this.table.setModel(dataModel);
        this.table.setDefaultEditor(Object.class, null);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
