/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import AccesoDatos.ProductModel;
import AccesoDatos.UserModel;
import java.util.ArrayList;

public class Invoice extends javax.swing.JFrame {

    private UserModel user;
    private ArrayList<ProductModel> products;

    public Invoice(ArrayList<ProductModel> products, UserModel user) {
        initComponents();
        this.user = user;
        this.setVisible(true);
        this.products = products;
        this.textArea.setText(createBill());
        
        this.setTitle("Factura");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("FreeMono", 0, 11)); // NOI18N
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String createBill() {
        StringBuilder sb = new StringBuilder();
        
        double subTotal = 0;

        sb.append("Factura para: " + this.user.getName());
        sb.append("\n");
        sb.append("\n");
        sb.append("\n");
        
        sb.append(createSpace("Nombre"));
        sb.append(createSpace("Precio $"));
        sb.append(createSpace("Cantidad"));
        sb.append(createSpace("Total"));
        sb.append("\n");

        for (ProductModel p : this.products) {
            String name = createSpace(p.getNombre());
            double price = p.getPrecio();
            String priceText = createSpace(String.valueOf(price));
            int amount = p.getStock();
            String amountText = createSpace(String.valueOf(amount));
            String total = createSpace(String.valueOf((price * amount)));
            
            subTotal+= (price * amount);

            sb.append(name);
            sb.append(priceText);
            sb.append(amountText);
            sb.append(total);

            sb.append("\n");
        }
        
        sb.append("\n");
        sb.append("\n");
        sb.append(createSpace("."));
        sb.append(createSpace("."));
        sb.append(createSpace("."));
        sb.append(createSpace("Subtotal"));
        sb.append("\n");
        sb.append("\n");
        
        sb.append(createSpace("."));
        sb.append(createSpace("."));
        sb.append(createSpace("."));
        sb.append(createSpace(String.valueOf(subTotal)));
        sb.append("\n");
        sb.append("\n");
        
        sb.append(createSpace("."));
        sb.append(createSpace("."));
        sb.append(createSpace("."));
        sb.append(createSpace("Impuesto"));
        sb.append("\n");
        sb.append("\n");
        
        sb.append(createSpace("."));
        sb.append(createSpace("."));
        sb.append(createSpace("."));
        sb.append(createSpace(String.valueOf(subTotal * .2)));
        sb.append("\n");
        sb.append("\n");
        
        sb.append(createSpace("."));
        sb.append(createSpace("."));
        sb.append(createSpace("."));
        sb.append(createSpace("Envio"));
        sb.append("\n");
        sb.append("\n");
        
        
        sb.append(createSpace("."));
        sb.append(createSpace("."));
        sb.append(createSpace("."));
        sb.append(createSpace(String.valueOf(subTotal * .3)));
        sb.append("\n");
        sb.append("\n");
        
        sb.append(createSpace("."));
        sb.append(createSpace("."));
        sb.append(createSpace("."));
        sb.append(createSpace("Total"));
        sb.append("\n");
        sb.append("\n");
        
        
        sb.append(createSpace("."));
        sb.append(createSpace("."));
        sb.append(createSpace("."));
        double total = (subTotal * .3) + (subTotal * .2) + subTotal;
        sb.append(createSpace(String.valueOf(total)));
        

        return sb.toString();
    }

    private String createSpace(String text) {
        StringBuilder sb = new StringBuilder();
        int spaces = 20;

        spaces -= text.length();

        sb.append(text);

        for (int i = 0; i < spaces; i++) {
            sb.append(" ");
        }

        return sb.toString();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
