
package Presentacion;

import AccesoDatos.UserModel;
import java.awt.event.WindowEvent;


/**
 *
 * @author carolina
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
    private UserModel user;
    
    public Principal(UserModel user) {
        initComponents();
        this.labelUser.setText("Welcome "+user.getName());
        
        if(user.getRole() != 0){
            this.JmSeguridad.setVisible(false);
        }
        
        this.user = user;
        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        labelUser = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JmSeguridad = new javax.swing.JMenu();
        JmMantenimiento = new javax.swing.JMenuItem();
        jMAdminUsers = new javax.swing.JMenuItem();
        jMcUser = new javax.swing.JMenu();
        jMchangeUser = new javax.swing.JMenuItem();
        JmExit = new javax.swing.JMenuItem();
        JmTienda = new javax.swing.JMenu();
        JmHistory = new javax.swing.JMenuItem();
        JmComprar = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("File");
        jMenuBar3.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar3.add(jMenu2);

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelUser.setBackground(new java.awt.Color(204, 204, 255));
        labelUser.setForeground(new java.awt.Color(0, 0, 0));
        labelUser.setText("Usuario");

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 153));

        JmSeguridad.setText("Seguridad");

        JmMantenimiento.setBackground(new java.awt.Color(153, 153, 255));
        JmMantenimiento.setText("Mantenimiento de Productos ");
        JmMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmMantenimientoActionPerformed(evt);
            }
        });
        JmSeguridad.add(JmMantenimiento);

        jMAdminUsers.setBackground(new java.awt.Color(153, 153, 255));
        jMAdminUsers.setForeground(new java.awt.Color(0, 0, 0));
        jMAdminUsers.setText("Mantenimiento Usuarios");
        jMAdminUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAdminUsersActionPerformed(evt);
            }
        });
        JmSeguridad.add(jMAdminUsers);

        jMenuBar1.add(JmSeguridad);

        jMcUser.setBackground(new java.awt.Color(102, 102, 255));
        jMcUser.setText("Usuarios");

        jMchangeUser.setBackground(new java.awt.Color(153, 153, 255));
        jMchangeUser.setText("CambiarUsuario");
        jMchangeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMchangeUserActionPerformed(evt);
            }
        });
        jMcUser.add(jMchangeUser);

        JmExit.setBackground(new java.awt.Color(153, 153, 255));
        JmExit.setText("Salir");
        JmExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmExitActionPerformed(evt);
            }
        });
        jMcUser.add(JmExit);

        jMenuBar1.add(jMcUser);

        JmTienda.setText("Tienda");

        JmHistory.setBackground(new java.awt.Color(153, 153, 255));
        JmHistory.setText("Historial");
        JmHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmHistoryActionPerformed(evt);
            }
        });
        JmTienda.add(JmHistory);

        JmComprar.setBackground(new java.awt.Color(153, 153, 255));
        JmComprar.setText("Comprar");
        JmComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmComprarActionPerformed(evt);
            }
        });
        JmTienda.add(JmComprar);

        jMenuBar1.add(JmTienda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUser)
                .addContainerGap(347, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUser)
                .addContainerGap(251, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JmMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmMantenimientoActionPerformed
        
        AdminProducts admin = new AdminProducts(this.user,this);
        
    }//GEN-LAST:event_JmMantenimientoActionPerformed

    private void JmComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmComprarActionPerformed
        
        StoreProducts store = new StoreProducts(this.user);
        
    }//GEN-LAST:event_JmComprarActionPerformed

    private void jMAdminUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAdminUsersActionPerformed
        AdminUsers admin = new AdminUsers(this.user);
    }//GEN-LAST:event_jMAdminUsersActionPerformed

    private void jMchangeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMchangeUserActionPerformed
      LogIn login = new LogIn();
      login.setVisible(true);
      this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jMchangeUserActionPerformed

    private void JmExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmExitActionPerformed
         System.exit(0);
    }//GEN-LAST:event_JmExitActionPerformed
    private void JmHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmHistoryActionPerformed
        
        HistorySales h = new HistorySales(this.user);
    }//GEN-LAST:event_JmHistoryActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JmComprar;
    private javax.swing.JMenuItem JmExit;
    private javax.swing.JMenuItem JmHistory;
    private javax.swing.JMenuItem JmMantenimiento;
    private javax.swing.JMenu JmSeguridad;
    private javax.swing.JMenu JmTienda;
    private javax.swing.JMenuItem jMAdminUsers;
    private javax.swing.JMenu jMcUser;
    private javax.swing.JMenuItem jMchangeUser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel labelUser;
    // End of variables declaration//GEN-END:variables
}
